name: prompt-search
channels:
  - defaults
dependencies:
  - python=3.7.13
  - pip=22.1.2
  - pip:
    - autofaiss==2.15.3
    - clip-by-openai==1.1
    - img2dataset==1.33.0
    - onnxruntime==1.12.1